import { useState, useCallback } from 'react'
import { PipelineProvider, usePipeline } from '@/contexts/PipelineContext'
import { SettingsProvider } from '@/contexts/SettingsContext'
import { AppLayout } from '@/components/layout/AppLayout'
import { PipelineControls } from '@/components/pipeline/PipelineControls'
import { ProgressBar } from '@/components/pipeline/ProgressBar'
import { TaskBoard } from '@/components/pipeline/TaskBoard'
import { EventFeed } from '@/components/pipeline/EventFeed'
import { DeveloperCards } from '@/components/developers/DeveloperCards'
import { ProviderSelect } from '@/components/settings/ProviderSelect'
import { ApiKeyManager } from '@/components/settings/ApiKeyManager'
import { ProjectLoader } from '@/components/settings/ProjectLoader'
import { CodeViewer } from '@/components/code/CodeViewer'
import { ExportPanel } from '@/components/export/ExportPanel'
import { useDevelopers } from '@/hooks/useDevelopers'
import './App.css'

type Tab = 'tasks' | 'code' | 'team' | 'export'

function TeamSidebarSection() {
  const { developers } = useDevelopers()
  return (
    <div className="dev-mini-list">
      {developers.map((d) => (
        <div key={d.id} className="dev-mini">
          <span className="dev-mini-status" data-disabled={!d.enabled} />
          <span>{d.emoji} {d.name}</span>
        </div>
      ))}
      {developers.length === 0 && (
        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Loading...</span>
      )}
    </div>
  )
}

function Dashboard() {
  const [activeTab, setActiveTab] = useState<Tab>('tasks')
  const [, setProjectPath] = useState('')
  const { events } = usePipeline()
  const handleProjectLoad = useCallback((path: string) => setProjectPath(path), [])

  // Collect generated files from code_generated events
  const generatedFiles: Record<string, string> = {}
  for (const ev of events) {
    if (ev.type === 'code_generated') {
      for (const f of ev.data.files) {
        generatedFiles[f] = generatedFiles[f] || '// Content generated by pipeline'
      }
    }
  }

  return (
    <AppLayout
      projectSection={<ProjectLoader onLoad={handleProjectLoad} />}
      providerSection={<ProviderSelect />}
      teamSection={<TeamSidebarSection />}
      settingsSection={<ApiKeyManager />}
      main={
        <>
          <PipelineControls />
          <ProgressBar />

          <div className="tabs" style={{ marginTop: '1rem' }}>
            {(['tasks', 'code', 'team', 'export'] as Tab[]).map((tab) => (
              <button
                key={tab}
                className="tab"
                data-active={activeTab === tab}
                onClick={() => setActiveTab(tab)}
              >
                {tab.charAt(0).toUpperCase() + tab.slice(1)}
              </button>
            ))}
          </div>

          {activeTab === 'tasks' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <TaskBoard />
              <EventFeed />
            </div>
          )}
          {activeTab === 'code' && <CodeViewer files={generatedFiles} />}
          {activeTab === 'team' && <DeveloperCards />}
          {activeTab === 'export' && <ExportPanel />}
        </>
      }
    />
  )
}

function App() {
  return (
    <SettingsProvider>
      <PipelineProvider>
        <Dashboard />
      </PipelineProvider>
    </SettingsProvider>
  )
}

export default App
